name: "Behavior"

web: "[clientcide.com](http://clientcide.com)"

description: "Behavior filters for MooTools More"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "1.1.2"

sources:
  - "Source/Delegator.js"
  - "Source/Element.Data.js"
  - "Source/Event.Mock.js"
  - "Source/Behavior.js"
  - "Source/BehaviorAPI.js"
  - "Source/Behavior.Startup.js"
  